### ISSUE TITLE
KeyError: 'totalNumberOfItems'

### ISSUE THREAD

**Issue by dgiglio** [clrxbl/tidal2spotify#1]
Hi, 
I'm using your code as example for a script of mine and this statement
`totalNumberOfItems = response.json()['totalNumberOfItems']`
returns the error in subject.
Thanks in advance

**Comment by clrxbl** [comment]
I built this tool ages ago when I needed something to convert from my Tidal account to Spotify. By now I wouldn't be surprised if Tidal or Spotify have changed their APIs resulting in this issue.

Unfortunately, I cannot be of assistance.
